- name: FastAPI OpenAPI Specs Generator
  # You may pin to the exact commit or the version.
  # uses: column-st/fastapi-openapi-specs-action@e0b4060bfa18a2d2795a4e596ee88ab551da1b20
  uses: column-st/fastapi-openapi-specs-action@v1.0.1
  with:
    # Command to use to install depedencies before running FastAPI application. This command gets ran as a standard shell command.

    installDepedencies: # optional, default is pip install -r requirements.txt
    # The directory in which the FastAPI Python app lives.  This should be the first folder in your project with a '__init__.py' file. Needed to do 'from project import app' in subsequent steps.

    moduleDir: 
    # The file in which your FastAPI application gets initialized from.

    fileName: # default is main.py
    # The name of the FastAPI object inside your '{moduleDir}/{fileName}.py'. This is used to do 'from {moduleDir}.{fileName} import {appName}'.

    appName: # default is app
    # Only use this if your application uses the 'fastapi-versioning' package.If the 'fastapi-versioning' is being used each version of your application has its own  individual FastAPI app that is ran in conjunction. This variable defines which FastAPI API  to use to generate the client. Use the package's VersionedFastAPI.prefix_format string,  something like 'v{number}' typically (e.g. 'v1').

    fastapiVersioning: # optional
    # The name of the output file. Do not include extension.
    outputName: # default is openapi
    # Output extension. May either be yaml or json.
    outputExtension: # default is yaml
